theme: jekyll-theme-minimal
title: [Qazaq IPTV]
logo: /assets/img/logo.png
description: [Qazaqstan tv/radio channels public m3u8 playlist]
show_downloads: [true]
github:
  m3u8_url: https://github.com/aidoseg/qazaqstan-tv/blob/main/Qazaqstan.m3u8?raw=true
