remote_theme: pages-themes/minimal@v0.2.0
title: Qazaq IPTV
logo: /assets/img/logo.png
description: Qazaqstan's public tv/radio m3u8 playlist
google_analytics: G-095S89JSFD
show_downloads: true
github:
  m3u8_url: https://aidoseg.github.io/qazaqiptv/playlist.m3u8
  repository_url: https://github.com/aidoseg/qazaqiptv/blob/gh-pages/playlist.m3u8
