name: Run Script with jq

on:
  schedule:
    - cron: '0 */8 * * *'  # Запуск каждые 8 часов

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Script
        run: |
          bash mkepg.sh > epgm.xml
          
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add epgm.xml
          git commit -m "Convert JSON to XMLTV"
          git push
