name: JSON to XMLTV Conversion Xabar 2

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install xmltodict

      - name: Convert JSON to XMLTV
        run: |
          wget -O xabar.json "https://epg.iptvx.one/api/id/xabar.json"
          python -c 'import xmltodict, json; print(xmltodict.unparse(json.load(open("xabar.json"))))' > epg.xml
          
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add epg.xml
          git commit -m "Convert JSON to XMLTV"
          git push
